export const mockData = {
    "automotive-industry": {
      name: "Automotive Industry",
      description:
        "The automotive sector is evolving with electric vehicles and AI-driven automation. Our data analytics help manufacturers and suppliers optimize logistics, improve safety, and enhance vehicle efficiency.",
      barData: [250, 180, 320],
      pieData: [50, 30, 20],
      lineData: [100, 200, 150, 250, 300],
      radarData: [80, 90, 70, 85, 95],
      keywords: ["automobile data", "car industry insights", "vehicle analytics"],
    },
  
    "banking-and-finance": {
      name: "Banking and Finance",
      description:
        "The finance industry thrives on data-driven decisions. From risk assessment to fraud detection, our database offers in-depth insights into financial transactions, customer trends, and market stability.",
      barData: [300, 220, 190],
      pieData: [40, 35, 25],
      lineData: [150, 250, 200, 300, 350],
      radarData: [85, 90, 80, 75, 95],
      keywords: ["banking analytics", "financial market insights", "investment trends"],
    },
  
    "construction-companies": {
      name: "Construction Companies",
      description:
        "Construction firms use our datasets to source materials, optimize project timelines, and identify emerging real estate trends.",
      barData: [200, 300, 250],
      pieData: [30, 40, 30],
      lineData: [120, 180, 220, 260, 300],
      radarData: [70, 85, 75, 80, 90],
      keywords: ["construction analytics", "building data insights", "real estate trends"],
    },
  
    "educational-industries": {
      name: "Educational Industries",
      description:
        "Education institutions leverage our datasets to identify student demographics, track e-learning adoption, and optimize course offerings.",
      barData: [180, 220, 240],
      pieData: [45, 30, 25],
      lineData: [150, 180, 230, 270, 310],
      radarData: [80, 85, 70, 75, 90],
      keywords: ["education data insights", "e-learning trends", "student analytics"],
    },
  
    "food-and-beverages": {
      name: "Food and Beverages",
      description:
        "From supply chain optimization to customer preferences, our food and beverage data helps businesses streamline operations and improve product offerings.",
      barData: [250, 300, 200],
      pieData: [50, 30, 20],
      lineData: [180, 230, 270, 300, 350],
      radarData: [75, 85, 80, 90, 95],
      keywords: ["food industry insights", "beverage market data", "restaurant analytics"],
    },
  
    "healthcare-industries": {
      name: "Healthcare Industries",
      description:
        "Healthcare data plays a crucial role in patient management, pharmaceutical research, and hospital efficiency. We provide extensive data insights to enhance patient care and operational workflows.",
      barData: [400, 300, 250],
      pieData: [50, 30, 20],
      lineData: [200, 300, 250, 350, 400],
      radarData: [90, 80, 85, 95, 100],
      keywords: ["healthcare big data", "hospital analytics", "medical data insights"],
    },
  
    "manufacturing-industries": {
      name: "Manufacturing Industries",
      description:
        "Our manufacturing datasets assist in supply chain management, labor efficiency tracking, and production optimization.",
      barData: [300, 220, 180],
      pieData: [45, 35, 20],
      lineData: [140, 190, 240, 290, 340],
      radarData: [85, 75, 80, 90, 95],
      keywords: ["manufacturing analytics", "factory production data", "supply chain insights"],
    },
  
    "oil-and-gas": {
      name: "Oil and Gas",
      description:
        "Energy companies leverage our data to optimize resource extraction, predict price fluctuations, and track industry regulations.",
      barData: [200, 400, 300],
      pieData: [50, 30, 20],
      lineData: [150, 250, 350, 400, 450],
      radarData: [80, 90, 85, 75, 95],
      keywords: ["oil industry analytics", "gas market trends", "energy data insights"],
    },
  
    "pharmaceuticals": {
      name: "Pharmaceuticals",
      description:
        "From drug development to prescription trends, our pharmaceutical data helps research firms and healthcare providers make informed decisions.",
      barData: [300, 200, 250],
      pieData: [40, 35, 25],
      lineData: [160, 220, 280, 320, 370],
      radarData: [85, 80, 75, 95, 100],
      keywords: ["pharmaceutical data", "drug market analytics", "healthcare research"],
    },
  
    "real-estate": {
      name: "Real Estate",
      description:
        "Our real estate data provides market insights, property valuation analytics, and buyer demographics for investors and agents.",
      barData: [250, 200, 300],
      pieData: [45, 30, 25],
      lineData: [140, 190, 250, 290, 330],
      radarData: [75, 80, 85, 90, 95],
      keywords: ["real estate market data", "property investment insights", "housing trends"],
    },
  
    "retail-industries": {
      name: "Retail Industries",
      description:
        "Retailers use our datasets to analyze shopping behavior, predict sales trends, and optimize inventory management.",
      barData: [300, 250, 200],
      pieData: [50, 30, 20],
      lineData: [180, 240, 280, 320, 360],
      radarData: [85, 80, 75, 95, 100],
      keywords: ["retail market analytics", "customer behavior insights", "ecommerce data"],
    },
  
    "travel-and-transport-industries": {
      name: "Travel and Transport Industries",
      description:
        "From airline ticketing to logistics management, our travel and transport data enhances operational efficiency and customer service.",
      barData: [200, 300, 260],
      pieData: [40, 35, 25],
      lineData: [160, 200, 260, 300, 340],
      radarData: [80, 85, 90, 75, 95],
      keywords: ["travel analytics", "transportation data insights", "logistics market trends"],
    },
  };
  export const CATEGORIES = [
  {
    title: "Healthcare",
    dataCount: "5,026,500",
    subCategories: [
      "Hospitals",
      "Clinics",
      "Pharmacies",
      "Medical Equipment Suppliers",
      "Health Insurance",
      "Physicians",
      "Nurses",
      "Therapists",
      "Diagnostics Labs",
      "Public Health Agencies",
    ],
  },
  {
    title: "Technology",
    dataCount:"2,566,372",
    subCategories: [
      "IT Services",
      "Software Development",
      "Hardware Suppliers",
      "Cloud Computing",
      "Cybersecurity",
      "Data Analytics",
      "Mobile App Development",
      "IoT Solutions",
      "Network Infrastructure",
      "SaaS Providers",
    ],
  },
  {
    title: "Finance",
    dataCount: "4,539,826",
    subCategories: [
      "Banks",
      "Investment Firms",
      "Credit Unions",
      "Insurance Companies",
      "Accounting Services",
      "Tax Consultants",
      "Wealth Management",
      "Mortgage Providers",
      "Payment Gateways",
      "Cryptocurrency Platforms",
    ],
  },
  {
    title: "Education",
    dataCount:"7,067,704" ,
    subCategories: [
      "Schools (K-12)",
      "Colleges",
      "Universities",
      "Online Learning Platforms",
      "Libraries",
      "Educational Consultants",
      "Tutoring Centers",
      "Training Institutes",
      "Student Organizations",
      "Research Centers",
    ],
  },
  {
    title: "Retail",
    dataCount: "1,850,923",
    subCategories: [
      "E-commerce Platforms",
      "Grocery Stores",
      "Fashion Retailers",
      "Electronics Stores",
      "Furniture Stores",
      "Automotive Retailers",
      "Department Stores",
      "Specialty Shops",
      "Wholesale Suppliers",
      "Shopping Malls",
    ],
  },
  {
    title: "Manufacturing",
    dataCount: "9,088,010",
    subCategories: [
      "Automotive Manufacturing",
      "Electronics Manufacturing",
      "Pharmaceutical Manufacturing",
      "Consumer Goods Manufacturing",
      "Heavy Machinery",
      "Textiles and Apparel",
      "Chemical Manufacturing",
      "Construction Materials",
      "Food and Beverage",
      "Packaging Industries",
    ],
  },
  {
    title: "Energy",
    dataCount: "5,062,600",
    subCategories: [
      "Oil and Gas",
      "Renewable Energy",
      "Power Plants",
      "Energy Consultants",
      "Utility Providers",
      "Energy Equipment Suppliers",
      "Green Energy Solutions",
      "Nuclear Energy",
      "Wind Energy",
      "Solar Energy",
    ],
  },
  {
    title: "Hospitality",
    dataCount: "10,050,900",
    subCategories: [
      "Hotels",
      "Restaurants",
      "Event Planners",
      "Travel Agencies",
      "Airlines",
      "Cruises",
      "Car Rentals",
      "Tour Operators",
      "Resorts",
      "Catering Services",
    ],
  },
  {
    title: "Real Estate",
    dataCount: "2,262,600",
    subCategories: [
      "Commercial Real Estate",
      "Residential Real Estate",
      "Real Estate Agents",
      "Property Management",
      "Real Estate Developers",
      "Mortgage Brokers",
      "Landlords",
      "Construction Companies",
      "Real Estate Investment Trusts (REITs)",
      "Appraisal Services",
    ],
  },
  {
    title: "Government",
    dataCount: "1,480,960",
    subCategories: [
      "Local Governments",
      "State Governments",
      "Federal Agencies",
      "Public Works",
      "Defense Departments",
      "Public Health Departments",
      "Environmental Agencies",
      "Transportation Departments",
      "Regulatory Bodies",
      "Law Enforcement",
    ],
  },
  {
    title: "Automotive",
    dataCount: "1,562,600",
    subCategories: [
      "Car Manufacturers",
      "Car Dealerships",
      "Auto Repair Services",
      "Tire Suppliers",
      "Spare Parts Suppliers",
      "Electric Vehicle Companies",
      "Fleet Management",
      "Automotive Research",
      "Auto Insurance Companies",
      "Logistics and Transport",
    ],
  },
  {
    title: "Telecommunications",
    dataCount: "2,010,550",
    subCategories: [
      "Mobile Network Providers",
      "Internet Service Providers",
      "Cable TV Operators",
      "Satellite Companies",
      "5G Solutions Providers",
      "Telecom Hardware Suppliers",
      "Call Centers",
      "VoIP Providers",
      "Broadband Providers",
      "Fiber Optics Companies",
    ],
  },
  {
    title: "Logistics",
    dataCount: "1,310,087",
    subCategories: [
      "Shipping Companies",
      "Freight Forwarders",
      "Courier Services",
      "Logistics Software Providers",
      "Warehousing Companies",
      "Supply Chain Management",
      "Port Authorities",
      "Customs Brokers",
      "3PL Companies",
      "Transportation Services",
    ],
  },
  {
    title: "Legal Services",
    dataCount: "1,690,180",
    subCategories: [
      "Law Firms",
      "Corporate Lawyers",
      "Family Lawyers",
      "Intellectual Property Lawyers",
      "Legal Tech Companies",
      "Notaries",
      "Compliance Officers",
      "Legal Consultancies",
      "Court Reporting Services",
      "Legal Translation Services",
    ],
  },
  {
    title: "Media and Entertainment",
    dataCount: "1,025,350",
    subCategories: [
      "Television Networks",
      "Radio Stations",
      "Streaming Platforms",
      "Film Production Companies",
      "Event Organizers",
      "Advertising Agencies",
      "Public Relations Agencies",
      "Graphic Designers",
      "Content Creators",
      "Media Distribution Companies",
    ],
  },
  {
    title: "Non-Profit",
    dataCount: "1,025,350",
    subCategories: [
      "Charities",
      "Foundations",
      "Community Organizations",
      "Environmental NGOs",
      "Religious Organizations",
      "Health-related NGOs",
      "Educational NGOs",
      "Human Rights Organizations",
      "Animal Welfare Groups",
      "International Aid Organizations",
    ],
  },
  {
    title: "Construction",
    dataCount: "2,095,180",
    subCategories: [
      "General Contractors",
      "Subcontractors",
      "Architectural Firms",
      "Civil Engineers",
      "Building Materials Suppliers",
      "Real Estate Developers",
      "Construction Equipment Suppliers",
      "Renovation Specialists",
      "Project Managers",
      "Interior Designers",
    ],
  },
  {
    title: "Food and Beverage",
    dataCount: "2,045,670",
    subCategories: [
      "Restaurants",
      "Fast Food Chains",
      "Cafes",
      "Food Distributors",
      "Beverage Companies",
      "Food Manufacturing",
      "Catering Services",
      "Vineyards and Breweries",
      "Food Delivery Services",
      "Specialty Food Stores",
    ],
  },]